export const API_ROUTES = {
    REGISTER: 'auth/register',
    LOGIN: 'auth/login',
    LOGOUT: 'auth/logout',
    REFRESH: 'auth/refresh',
    GET_ACCOUNT: 'auth/me',
    TWEET_SEARCH: "tweets:search",
    FOLLOWING_TWEETS: 'account/following/tweets',
    TWEETS: 'tweets',
    ACCOUNT_FOLLOWERS: "users/me/followers",
    ACCOUNT_FOLLOWING: "users/me/followings",
    RECOMMENDATION_ACCOUNTS: 'users/me/recommendation',
    ACCOUNT_FOLLOW: 'users/follow',
    ACCOUNT_UNFOLLOW: 'users/unfollow',
    USERS: 'users',
    INIT_CHAT: 'chats/init',
    CHAT_MESSAGES: 'chats/messages',
    CHAT_SEARCH_MESSAGES: 'chats/messages:search',

}
